{"cells":[{"cell_type":"markdown","metadata":{"id":"e7JowRQEGGKQ"},"source":["> # **Clone GitHub repository**"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"IyGzuEMQF6sJ","outputId":"24315774-f954-409b-e329-b6f34c21a71f"},"outputs":[{"name":"stdout","output_type":"stream","text":["============================================================================================\n","Cloning into 'PPO-PyTorch'...\n"]}],"source":["\n","################# Clone repository from github to colab session ################\n","\n","\"\"\"\n","\n","run this section if you want to clone all the preTrained networks, logs, graph figures, gifs\n","from the GitHub repository to this colab session\n","\n","\"\"\"\n","\n","\n","print(\"============================================================================================\")\n","\n","!git clone https://github.com/nikhilbarhate99/PPO-PyTorch\n","\n","print(\"============================================================================================\")\n","\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Mrn6rpJpF8Sc"},"outputs":[],"source":["\n","\"\"\"\n","\n","run this section if you want to copy all files and folders from cloned folder (PPO-PyTorch)\n","to current directory (/content/ or ./)\n","\n","So you can load preTrained networks and log files without changing any paths\n","\n","**  This will overwrite any saved networks, logs, graph figures, or gifs\n","    that are created in this session before copying having the same name (or number)\n","\n","\"\"\"\n","\n","print(\"============================================================================================\")\n","\n","!cp -rv ./PPO-PyTorch/* ./\n","\n","print(\"============================================================================================\")\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"X-7AbGA2F8Ut"},"outputs":[],"source":["\n","\"\"\"\n","\n","run this section if you want to delete original cloned folder and the cloned ipynb file\n","(after you have copied its contents to current directory)\n","\n","\"\"\"\n","\n","\n","print(\"============================================================================================\")\n","\n","# delete original cloned folder\n","!rm -r ./PPO-PyTorch\n","\n","# delete cloned ipynb file\n","!rm ./PPO_colab.ipynb\n","\n","print(\"============================================================================================\")\n","\n"]},{"cell_type":"markdown","metadata":{"id":"Z4VJcUT2GlJz"},"source":["> # **Install Dependencies**"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"rbpSQTflGlAr"},"outputs":[],"source":["\n","\n","############ install compatible version of OpenAI roboschool and gym ###########\n","\n","!pip install swig\n","\n","# !pip install roboschool==1.0.7 gym==0.15.4\n","\n","# !pip install box2d-py\n","\n","# !pip install Box2D\n","\n","# !pip install pybullet\n","\n","# !pip install gym[box2d]\n"]},{"cell_type":"markdown","metadata":{"id":"pzZairIiGQ11"},"source":["> # **Introduction**\n","> The notebook is divided into 5 major parts :\n","\n","*   **Part I** : define actor-critic network and PPO algorithm\n","*   **Part II** : train PPO algorithm and save network weights and log files\n","*   **Part III** : load (preTrained) network weights and test PPO algorithm\n","*   **Part IV** : load log files and plot graphs\n","*   **Part V** : install xvbf, load (preTrained) network weights and save images for gif and then generate gif"]},{"cell_type":"markdown","metadata":{"id":"tsVBou8l2qq_"},"source":["# Import\n"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true},"id":"aY02DH-O2ru-","outputId":"9736c0a1-7af6-4ff9-f5ff-e4e1b58d196d"},"outputs":[{"name":"stdout","output_type":"stream","text":["Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/\n","Requirement already satisfied: fmpy in /usr/local/lib/python3.10/dist-packages (0.3.15)\n","Requirement already satisfied: attrs in /usr/local/lib/python3.10/dist-packages (from fmpy) (23.1.0)\n","Requirement already satisfied: Jinja2 in /usr/local/lib/python3.10/dist-packages (from fmpy) (3.1.2)\n","Requirement already satisfied: lark in /usr/local/lib/python3.10/dist-packages (from fmpy) (1.1.5)\n","Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from fmpy) (4.9.2)\n","Requirement already satisfied: msgpack in /usr/local/lib/python3.10/dist-packages (from fmpy) (1.0.5)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from fmpy) (1.22.4)\n","Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from fmpy) (2022.7.1)\n","Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2->fmpy) (2.1.2)\n"]},{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Mounted at /content/drive/\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-14-95aa14a54388>\", line 6, in <cell line: 6>\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/Colab Notebooks/0513/baseline0513')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-14-95aa14a54388>\", line 6, in <cell line: 6>\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/Colab Notebooks/0513/baseline0513')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-14-95aa14a54388>\", line 6, in <cell line: 6>\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/Colab Notebooks/0513/baseline0513')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["!pip install fmpy\n","\n","from google.colab import drive\n","drive.mount('/content/drive/', force_remount=True)\n","\n","%cd /content/drive/MyDrive/Colab Notebooks/0513/baseline0513\n","\n","from fmpy import read_model_description, extract\n","from fmpy.fmi2 import FMU2Slave\n","from fmpy.util import plot_result, download_test_file\n","import numpy as np\n","import pandas as pd\n","import shutil\n","import matplotlib.pyplot as plt\n","\n","import random\n","\n","import torch\n","import argparse\n","import os\n","import sys\n","\n","import tensorflow as tf\n","\n","from collections import deque\n","\n","from tqdm import tqdm\n","\n","from tensorflow import keras\n","from tensorflow.keras import layers\n","\n","import scipy.signal\n","import time\n","import torch.nn as nn\n","import torch.nn.functional as F\n","from torch.distributions.normal import Normal\n","from torch import FloatTensor as FT\n","import tensorflow_probability as tfp\n","import torch.optim as optim\n","from torch.distributions import Normal"]},{"cell_type":"markdown","metadata":{"id":"e6EFbxTo200G"},"source":["# HEV"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true},"id":"xn08jXE824HO","outputId":"d842df12-dae8-47d1-d284-764e473a0128"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-14-1bfa5dc9765e>\", line 8, in <cell line: 8>\n","    with open(\"wltp_vehicle_speed_profile_real.csv\") as file_name:\n","OSError: [Errno 107] Transport endpoint is not connected: 'wltp_vehicle_speed_profile_real.csv'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-14-1bfa5dc9765e>\", line 8, in <cell line: 8>\n","    with open(\"wltp_vehicle_speed_profile_real.csv\") as file_name:\n","OSError: [Errno 107] Transport endpoint is not connected: 'wltp_vehicle_speed_profile_real.csv'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-14-1bfa5dc9765e>\", line 8, in <cell line: 8>\n","    with open(\"wltp_vehicle_speed_profile_real.csv\") as file_name:\n","OSError: [Errno 107] Transport endpoint is not connected: 'wltp_vehicle_speed_profile_real.csv'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["fmu_filename = 'HEV_TMED_Simulator_Rearrange_230511_linux.fmu'\n","start_time = 0.0\n","stop_time = 1800.0\n","step_size = 0.01\n","soc_init = 67\n","\n","# WLTP profile에 대하여 시험\n","with open(\"wltp_vehicle_speed_profile_real.csv\") as file_name:\n","    vehicle_speed_profile = np.loadtxt(file_name, delimiter=\",\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"rS5qT1-926kl"},"outputs":[],"source":["class HEV:\n","    def __init__(self, fmu_filename, start_time, stop_time, step_size, soc_init, vehicle_speed_profile):\n","        self.fmu_filename = fmu_filename\n","        self.vrs = {}\n","        self.start_time = start_time\n","        self.stop_time = stop_time\n","        self.step_size = step_size\n","        self.time = self.start_time\n","        self.vehicle_speed_profile = vehicle_speed_profile\n","        self.soc_init = soc_init/5000\n","        self.state_init = np.array([self.soc_init, 0, 0, 0, 0, 0, 0, 0, 0]).reshape(1,-1)\n","        self.state = np.array([self.soc_init, 0, 0, 0, 0, 0, 0, 0, 0]).reshape(1,-1)\n","        self.action_upper_bound = 15000\n","        self.action_lower_bound = -15000\n","        #self.action_space = [[13500, 2000], [500, 2000], [13500, -15000], [500, -15000]]\n","        self.obssize = len(self.state[0])\n","        self.actsize = 2\n","\n","    def step(self, action):\n","        #a = self.action_space[action]\n","#         action = action*self.action_upper_bound\n","        a1 = action[0]*self.action_upper_bound\n","        a2 = action[0]*self.action_upper_bound\n","        a3 = self.soc_init\n","        a4 = action[1]/10 + 1\n","        instant_veh_speed = np.interp(self.time, self.vehicle_speed_profile[:,0], self.vehicle_speed_profile[:,1])\n","        self.fmu.setReal([self.vr_input1, self.vr_input2, self.vr_input3, self.vr_input4, self.vr_input5], [instant_veh_speed, a1, a2, a3, a4]) #input variable, input key(13500 2000)\n","        self.fmu.doStep(currentCommunicationPoint=self.time, communicationStepSize=self.step_size)\n","#         [output1, output2, output3, output4, output5, output6, output7] = self.fmu.getReal([self.vr_output1,self.vr_output2, self.vr_output3, self.vr_output4, self.vr_output5, self.vr_output6, self.vr_output7])\n","#         self.state = [output1, output2, output3, output4, output5, output6, output7]\n","        state = np.array(self.fmu.getReal(np.arange(35)))/5000\n","        state_column = np.array([self.vrs['Bat_SOC'], self.vrs['nEngOn'], self.vrs['PT_tqTmInDmd_Nm_P2'], self.vrs['ObEng_nEng_Rpm'], self.vrs['TrEtp_tqEngMAF_Nm'], self.vrs['TrP0_tqP0_Nm'], self.vrs['TrP2_tqP2_Nm'], self.vrs['Driver_sVeh_kph'], self.vrs['BSFC_g_kWh[1]']])\n","        self.state = state[state_column]\n","        soc = state[self.vrs['Bat_SOC']]\n","        BSFC = state[self.vrs['BSFC_g_kWh[1]']]\n","        reward = - 5000*(self.soc_init - soc) ** 2 - 10*BSFC\n","        is_done = lambda time: time >= self.stop_time\n","        self.time += self.step_size\n","        return self.state.reshape(1,-1), reward, is_done(self.time), None\n","\n","    def reset(self):\n","        self.state = self.state_init\n","        model_description = read_model_description(self.fmu_filename)\n","        for variable in model_description.modelVariables:\n","            self.vrs[variable.name] = variable.valueReference\n","        unzipdir = extract(fmu_filename)\n","        self.fmu = FMU2Slave(guid=model_description.guid,\n","                       unzipDirectory=unzipdir,\n","                       modelIdentifier=model_description.coSimulation.modelIdentifier,\n","                       instanceName='instance1')\n","        self.fmu.instantiate()\n","        self.fmu.setupExperiment(startTime=self.start_time)\n","        self.fmu.enterInitializationMode()\n","        self.fmu.exitInitializationMode()\n","        self.time = self.start_time\n","\n","        self.vr_input1 = self.vrs['Driver_sVeh_Target_kph']\n","        self.vr_input2 = self.vrs['Engine_on_line']\n","        self.vr_input3 = self.vrs['Engine_off_line']\n","        self.vr_input4 = self.vrs['soc_init']\n","        self.vr_input5 = self.vrs['Engine_OOL']\n","        self.vr_output1 = self.vrs['TgMod_fPt']\n","        self.vr_output2 = self.vrs['P2_wElec_W']\n","        self.vr_output3 = self.vrs['P4_wElec_W']\n","        self.vr_output4 = self.vrs['ObP2_wElecBIntv_W']\n","        self.vr_output5 = self.vrs['EV_on_line']\n","        self.vr_output6 = self.vrs['EV_off_line']\n","        self.vr_output7 = self.vrs['Bat_SOC']\n","        self.vr_output8 = self.vrs['PT_tqTmInDmd_Nm_P2']\n","        self.vr_output9 = self.vrs['P0_wElec_W']\n","        self.vr_output10 = self.vrs['Pwr_Aux_W']\n","        self.vr_output11 = self.vrs['ObEng_nEng_Rpm']\n","        self.vr_output12 = self.vrs['TrEtp_tqEngMAF_Nm']\n","        self.vr_output13 = self.vrs['rpm_P0']\n","        self.vr_output14 = self.vrs['TM_F_nTmIn_rpm']\n","        self.vr_output15 = self.vrs['TM_R_nTmIn_rpm']\n","        self.vr_output16 = self.vrs['eBat_kWh']\n","        self.vr_output17 = self.vrs['nEngOn']\n","        self.vr_output18 = self.vrs['TrP0_tqP0_Nm']\n","        self.vr_output19 = self.vrs['TrP2_tqP2_Nm']\n","        self.vr_output20 = self.vrs['TrP4_tqP4_Nm']\n","        self.vr_output21 = self.vrs['TCU_F_fCurGe']\n","        self.vr_output22 = self.vrs['TCU_F_fTarGe']\n","        self.vr_output23 = self.vrs['Driver_sVeh_kph']\n","        self.vr_output24 = self.vrs['Eng_eff_avg']\n","        self.vr_output25 = self.vrs['TM_F_P0P2_eff_avg']\n","        self.vr_output26 = self.vrs['TM_F_P0P4_eff_avg']\n","        self.vr_output27 = self.vrs['BSFC_g_kWh[1]']\n","        self.vr_output28 = self.vrs['BSFC_g_kWh[2]']\n","        self.vr_output29 = self.vrs['BSFC_g_kWh[3]']\n","\n","        return self.state.reshape(1,-1)"]},{"cell_type":"markdown","metadata":{"id":"s37cJXAYGrTY"},"source":["> # **Part - I**\n","\n","*   define actor critic networks\n","*   define PPO algorithm\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"UT6VUBg-F8Zm"},"outputs":[],"source":["\n","\n","############################### Import libraries ###############################\n","\n","\n","import os\n","import glob\n","import time\n","from datetime import datetime\n","\n","import torch\n","import torch.nn as nn\n","from torch.distributions import MultivariateNormal\n","from torch.distributions import Categorical\n","\n","import numpy as np\n","\n","# import gym\n","# import roboschool\n","# import pybullet_envs\n","\n","\n","################################## set device ##################################\n","\n","print(\"============================================================================================\")\n","\n","\n","# set device to cpu or cuda\n","device = torch.device('cpu')\n","\n","if(torch.cuda.is_available()):\n","    device = torch.device('cuda:0')\n","    torch.cuda.empty_cache()\n","    print(\"Device set to : \" + str(torch.cuda.get_device_name(device)))\n","else:\n","    print(\"Device set to : cpu\")\n","\n","print(\"============================================================================================\")\n","\n","\n","\n","\n","################################## PPO Policy ##################################\n","\n","\n","class RolloutBuffer:\n","    def __init__(self):\n","        self.actions = []\n","        self.states = []\n","        self.logprobs = []\n","        self.rewards = []\n","        self.state_values = []\n","        self.is_terminals = []\n","\n","\n","    def clear(self):\n","        del self.actions[:]\n","        del self.states[:]\n","        del self.logprobs[:]\n","        del self.rewards[:]\n","        del self.state_values[:]\n","        del self.is_terminals[:]\n","\n","\n","class ActorCritic(nn.Module):\n","    def __init__(self, state_dim, action_dim, has_continuous_action_space, action_std_init):\n","        super(ActorCritic, self).__init__()\n","\n","        self.has_continuous_action_space = has_continuous_action_space\n","\n","        if has_continuous_action_space:\n","            self.action_dim = action_dim\n","            self.action_var = torch.full((action_dim,), action_std_init * action_std_init).to(device)\n","\n","        # actor\n","        if has_continuous_action_space :\n","            self.actor = nn.Sequential(\n","                            nn.Linear(state_dim, 64),\n","                            nn.Tanh(),\n","                            nn.Linear(64, 64),\n","                            nn.Tanh(),\n","                            nn.Linear(64, action_dim),\n","                            nn.Tanh()\n","                        )\n","        else:\n","            self.actor = nn.Sequential(\n","                            nn.Linear(state_dim, 64),\n","                            nn.Tanh(),\n","                            nn.Linear(64, 64),\n","                            nn.Tanh(),\n","                            nn.Linear(64, action_dim),\n","                            nn.Softmax(dim=-1)\n","                        )\n","\n","\n","        # critic\n","        self.critic = nn.Sequential(\n","                        nn.Linear(state_dim, 64),\n","                        nn.Tanh(),\n","                        nn.Linear(64, 64),\n","                        nn.Tanh(),\n","                        nn.Linear(64, 1)\n","                    )\n","\n","    def set_action_std(self, new_action_std):\n","\n","        if self.has_continuous_action_space:\n","            self.action_var = torch.full((self.action_dim,), new_action_std * new_action_std).to(device)\n","        else:\n","            print(\"--------------------------------------------------------------------------------------------\")\n","            print(\"WARNING : Calling ActorCritic::set_action_std() on discrete action space policy\")\n","            print(\"--------------------------------------------------------------------------------------------\")\n","\n","\n","    def forward(self):\n","        raise NotImplementedError\n","\n","\n","    def act(self, state):\n","\n","        if self.has_continuous_action_space:\n","            action_mean = self.actor(state)\n","            cov_mat = torch.diag(self.action_var).unsqueeze(dim=0)\n","            dist = MultivariateNormal(action_mean, cov_mat)\n","        else:\n","            action_probs = self.actor(state)\n","            dist = Categorical(action_probs)\n","\n","        action = dist.sample()\n","        action_logprob = dist.log_prob(action)\n","        state_val = self.critic(state)\n","\n","        return action.detach(), action_logprob.detach(), state_val.detach()\n","\n","\n","    def evaluate(self, state, action):\n","\n","        if self.has_continuous_action_space:\n","            action_mean = self.actor(state)\n","            action_var = self.action_var.expand_as(action_mean)\n","            cov_mat = torch.diag_embed(action_var).to(device)\n","            dist = MultivariateNormal(action_mean, cov_mat)\n","\n","            # for single action continuous environments\n","            if self.action_dim == 1:\n","                action = action.reshape(-1, self.action_dim)\n","\n","        else:\n","            action_probs = self.actor(state)\n","            dist = Categorical(action_probs)\n","\n","        action_logprobs = dist.log_prob(action)\n","        dist_entropy = dist.entropy()\n","        state_values = self.critic(state)\n","\n","        return action_logprobs, state_values, dist_entropy\n","\n","\n","class PPO:\n","    def __init__(self, state_dim, action_dim, lr_actor, lr_critic, gamma, K_epochs, eps_clip, has_continuous_action_space, action_std_init=0.6):\n","\n","        self.has_continuous_action_space = has_continuous_action_space\n","\n","        if has_continuous_action_space:\n","            self.action_std = action_std_init\n","\n","        self.gamma = gamma\n","        self.eps_clip = eps_clip\n","        self.K_epochs = K_epochs\n","\n","        self.buffer = RolloutBuffer()\n","\n","        self.policy = ActorCritic(state_dim, action_dim, has_continuous_action_space, action_std_init).to(device)\n","        self.optimizer = torch.optim.Adam([\n","                        {'params': self.policy.actor.parameters(), 'lr': lr_actor},\n","                        {'params': self.policy.critic.parameters(), 'lr': lr_critic}\n","                    ])\n","\n","        self.policy_old = ActorCritic(state_dim, action_dim, has_continuous_action_space, action_std_init).to(device)\n","        self.policy_old.load_state_dict(self.policy.state_dict())\n","\n","        self.MseLoss = nn.MSELoss()\n","\n","\n","    def set_action_std(self, new_action_std):\n","\n","        if self.has_continuous_action_space:\n","            self.action_std = new_action_std\n","            self.policy.set_action_std(new_action_std)\n","            self.policy_old.set_action_std(new_action_std)\n","\n","        else:\n","            print(\"--------------------------------------------------------------------------------------------\")\n","            print(\"WARNING : Calling PPO::set_action_std() on discrete action space policy\")\n","            print(\"--------------------------------------------------------------------------------------------\")\n","\n","\n","    def decay_action_std(self, action_std_decay_rate, min_action_std):\n","        print(\"--------------------------------------------------------------------------------------------\")\n","\n","        if self.has_continuous_action_space:\n","            self.action_std = self.action_std - action_std_decay_rate\n","            self.action_std = round(self.action_std, 4)\n","            if (self.action_std <= min_action_std):\n","                self.action_std = min_action_std\n","                print(\"setting actor output action_std to min_action_std : \", self.action_std)\n","            else:\n","                print(\"setting actor output action_std to : \", self.action_std)\n","            self.set_action_std(self.action_std)\n","\n","        else:\n","            print(\"WARNING : Calling PPO::decay_action_std() on discrete action space policy\")\n","\n","        print(\"--------------------------------------------------------------------------------------------\")\n","\n","\n","    def select_action(self, state):\n","\n","        if self.has_continuous_action_space:\n","            with torch.no_grad():\n","                state = torch.FloatTensor(state).to(device)\n","                action, action_logprob, state_val = self.policy_old.act(state)\n","\n","            self.buffer.states.append(state)\n","            self.buffer.actions.append(action)\n","            self.buffer.logprobs.append(action_logprob)\n","            self.buffer.state_values.append(state_val)\n","\n","            return action.detach().cpu().numpy().flatten()\n","\n","        else:\n","            with torch.no_grad():\n","                state = torch.FloatTensor(state).to(device)\n","                action, action_logprob, state_val = self.policy_old.act(state)\n","\n","            self.buffer.states.append(state)\n","            self.buffer.actions.append(action)\n","            self.buffer.logprobs.append(action_logprob)\n","            self.buffer.state_values.append(state_val)\n","\n","            return action.item()\n","\n","\n","    def update(self):\n","\n","        # Monte Carlo estimate of returns\n","        rewards = []\n","        discounted_reward = 0\n","        for reward, is_terminal in zip(reversed(self.buffer.rewards), reversed(self.buffer.is_terminals)):\n","            if is_terminal:\n","                discounted_reward = 0\n","            discounted_reward = reward + (self.gamma * discounted_reward)\n","            rewards.insert(0, discounted_reward)\n","\n","        # Normalizing the rewards\n","        rewards = torch.tensor(rewards, dtype=torch.float32).to(device)\n","        rewards = (rewards - rewards.mean()) / (rewards.std() + 1e-7)\n","\n","        # convert list to tensor\n","        old_states = torch.squeeze(torch.stack(self.buffer.states, dim=0)).detach().to(device)\n","        old_actions = torch.squeeze(torch.stack(self.buffer.actions, dim=0)).detach().to(device)\n","        old_logprobs = torch.squeeze(torch.stack(self.buffer.logprobs, dim=0)).detach().to(device)\n","        old_state_values = torch.squeeze(torch.stack(self.buffer.state_values, dim=0)).detach().to(device)\n","\n","        # calculate advantages\n","        advantages = rewards.detach() - old_state_values.detach()\n","\n","\n","        # Optimize policy for K epochs\n","        for _ in range(self.K_epochs):\n","\n","            # Evaluating old actions and values\n","            logprobs, state_values, dist_entropy = self.policy.evaluate(old_states, old_actions)\n","\n","            # match state_values tensor dimensions with rewards tensor\n","            state_values = torch.squeeze(state_values)\n","\n","            # Finding the ratio (pi_theta / pi_theta__old)\n","            ratios = torch.exp(logprobs - old_logprobs.detach())\n","\n","            # Finding Surrogate Loss\n","            surr1 = ratios * advantages\n","            surr2 = torch.clamp(ratios, 1-self.eps_clip, 1+self.eps_clip) * advantages\n","\n","            # final loss of clipped objective PPO\n","            loss = -torch.min(surr1, surr2) + 0.5 * self.MseLoss(state_values, rewards) - 0.01 * dist_entropy\n","\n","            # take gradient step\n","            self.optimizer.zero_grad()\n","            loss.mean().backward()\n","            self.optimizer.step()\n","\n","        # Copy new weights into old policy\n","        self.policy_old.load_state_dict(self.policy.state_dict())\n","\n","        # clear buffer\n","        self.buffer.clear()\n","\n","\n","    def save(self, checkpoint_path):\n","        torch.save(self.policy_old.state_dict(), checkpoint_path)\n","\n","\n","    def load(self, checkpoint_path):\n","        self.policy_old.load_state_dict(torch.load(checkpoint_path, map_location=lambda storage, loc: storage))\n","        self.policy.load_state_dict(torch.load(checkpoint_path, map_location=lambda storage, loc: storage))\n","\n","\n","\n","\n"]},{"cell_type":"markdown","metadata":{"id":"yr-ZjT_CGyEi"},"source":["> # **Part - II**\n","\n","*   train PPO algorithm on environments\n","*   save preTrained networks weights and log files"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true},"id":"YY1-DzVCF8eh","outputId":"ffe8c3f0-020e-4e19-e5ce-7cde5c751e73"},"outputs":[{"name":"stdout","output_type":"stream","text":["============================================================================================\n","training environment name : HEV\n"]},{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-16-3cbb1c48192a>\", line 68, in <cell line: 67>\n","    os.makedirs(log_dir)\n","  File \"/usr/lib/python3.10/os.py\", line 225, in makedirs\n","    mkdir(name, mode)\n","OSError: [Errno 107] Transport endpoint is not connected: 'PPO_logs'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-16-3cbb1c48192a>\", line 68, in <cell line: 67>\n","    os.makedirs(log_dir)\n","  File \"/usr/lib/python3.10/os.py\", line 225, in makedirs\n","    mkdir(name, mode)\n","OSError: [Errno 107] Transport endpoint is not connected: 'PPO_logs'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-16-3cbb1c48192a>\", line 68, in <cell line: 67>\n","    os.makedirs(log_dir)\n","  File \"/usr/lib/python3.10/os.py\", line 225, in makedirs\n","    mkdir(name, mode)\n","OSError: [Errno 107] Transport endpoint is not connected: 'PPO_logs'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["\n","print(\"============================================================================================\")\n","\n","\n","################################### Training ###################################\n","\n","\n","####### initialize environment hyperparameters ######\n","\n","env_name = \"HEV\"\n","has_continuous_action_space = True\n","\n","max_ep_len = 180001                    # max timesteps in one episode\n","max_training_timesteps = int(max_ep_len*50)   # break training loop if timeteps > max_training_timesteps\n","\n","print_freq = max_ep_len * 1     # print avg reward in the interval (in num timesteps)\n","log_freq = max_ep_len * 1       # log avg reward in the interval (in num timesteps)\n","save_model_freq = int(max_ep_len)      # save model frequency (in num timesteps)\n","\n","action_std = 0.6                    # starting std for action distribution (Multivariate Normal)\n","action_std_decay_rate = 0.05        # linearly decay action_std (action_std = action_std - action_std_decay_rate)\n","min_action_std = 0.1                # minimum action_std (stop decay after action_std <= min_action_std)\n","action_std_decay_freq = int(5 * max_ep_len)  # action_std decay frequency (in num timesteps)\n","\n","#####################################################\n","\n","\n","## Note : print/log frequencies should be > than max_ep_len\n","\n","\n","################ PPO hyperparameters ################\n","\n","\n","update_timestep = max_ep_len * 5      # update policy every n timesteps\n","K_epochs = 40               # update policy for K epochs\n","eps_clip = 0.2              # clip parameter for PPO\n","gamma = 0.99                # discount factor\n","\n","lr_actor = 0.0003       # learning rate for actor network\n","lr_critic = 0.001       # learning rate for critic network\n","\n","random_seed = 0         # set random seed if required (0 = no random seed)\n","\n","#####################################################\n","\n","\n","\n","print(\"training environment name : \" + env_name)\n","\n","env = HEV(fmu_filename, start_time, stop_time, step_size, soc_init, vehicle_speed_profile)\n","\n","# state space dimension\n","state_dim = env.obssize\n","\n","# action space dimension\n","if has_continuous_action_space:\n","    action_dim = env.actsize\n","else:\n","    action_dim = env.action_space.n\n","\n","\n","\n","###################### logging ######################\n","\n","#### log files for multiple runs are NOT overwritten\n","\n","log_dir = \"PPO_logs\"\n","if not os.path.exists(log_dir):\n","      os.makedirs(log_dir)\n","\n","log_dir = log_dir + '/' + env_name + '/'\n","if not os.path.exists(log_dir):\n","      os.makedirs(log_dir)\n","\n","\n","#### get number of log files in log directory\n","run_num = 0\n","current_num_files = next(os.walk(log_dir))[2]\n","run_num = len(current_num_files)\n","\n","\n","#### create new log file for each run\n","log_f_name = log_dir + '/PPO_' + env_name + \"_log_\" + str(run_num) + \".csv\"\n","\n","print(\"current logging run number for \" + env_name + \" : \", run_num)\n","print(\"logging at : \" + log_f_name)\n","\n","#####################################################\n","\n","\n","################### checkpointing ###################\n","\n","run_num_pretrained = 0      #### change this to prevent overwriting weights in same env_name folder\n","\n","directory = \"PPO_preTrained\"\n","if not os.path.exists(directory):\n","      os.makedirs(directory)\n","\n","directory = directory + '/' + env_name + '/'\n","if not os.path.exists(directory):\n","      os.makedirs(directory)\n","\n","\n","checkpoint_path = directory + \"PPO_{}_{}_{}.pth\".format(env_name, random_seed, run_num_pretrained)\n","print(\"save checkpoint path : \" + checkpoint_path)\n","\n","#####################################################\n","\n","\n","############# print all hyperparameters #############\n","\n","print(\"--------------------------------------------------------------------------------------------\")\n","\n","print(\"max training timesteps : \", max_training_timesteps)\n","print(\"max timesteps per episode : \", max_ep_len)\n","\n","print(\"model saving frequency : \" + str(save_model_freq) + \" timesteps\")\n","print(\"log frequency : \" + str(log_freq) + \" timesteps\")\n","print(\"printing average reward over episodes in last : \" + str(print_freq) + \" timesteps\")\n","\n","print(\"--------------------------------------------------------------------------------------------\")\n","\n","print(\"state space dimension : \", state_dim)\n","print(\"action space dimension : \", action_dim)\n","\n","print(\"--------------------------------------------------------------------------------------------\")\n","\n","if has_continuous_action_space:\n","    print(\"Initializing a continuous action space policy\")\n","    print(\"--------------------------------------------------------------------------------------------\")\n","    print(\"starting std of action distribution : \", action_std)\n","    print(\"decay rate of std of action distribution : \", action_std_decay_rate)\n","    print(\"minimum std of action distribution : \", min_action_std)\n","    print(\"decay frequency of std of action distribution : \" + str(action_std_decay_freq) + \" timesteps\")\n","\n","else:\n","    print(\"Initializing a discrete action space policy\")\n","\n","print(\"--------------------------------------------------------------------------------------------\")\n","\n","print(\"PPO update frequency : \" + str(update_timestep) + \" timesteps\")\n","print(\"PPO K epochs : \", K_epochs)\n","print(\"PPO epsilon clip : \", eps_clip)\n","print(\"discount factor (gamma) : \", gamma)\n","\n","print(\"--------------------------------------------------------------------------------------------\")\n","\n","print(\"optimizer learning rate actor : \", lr_actor)\n","print(\"optimizer learning rate critic : \", lr_critic)\n","\n","if random_seed:\n","    print(\"--------------------------------------------------------------------------------------------\")\n","    print(\"setting random seed to \", random_seed)\n","    torch.manual_seed(random_seed)\n","    env.seed(random_seed)\n","    np.random.seed(random_seed)\n","\n","#####################################################\n","\n","print(\"============================================================================================\")\n","\n","################# training procedure ################\n","\n","# initialize a PPO agent\n","ppo_agent = PPO(state_dim, action_dim, lr_actor, lr_critic, gamma, K_epochs, eps_clip, has_continuous_action_space, action_std)\n","\n","\n","# track total training time\n","start_time = datetime.now().replace(microsecond=0)\n","print(\"Started training at (GMT) : \", start_time)\n","\n","print(\"============================================================================================\")\n","\n","\n","# logging file\n","log_f = open(log_f_name,\"w+\")\n","log_f.write('episode,timestep,reward\\n')\n","\n","\n","# printing and logging variables\n","print_running_reward = 0\n","print_running_episodes = 1\n","\n","log_running_reward = 0\n","log_running_episodes = 1\n","\n","time_step = 0\n","i_episode = 0\n","\n","\n","# training loop\n","while time_step <= max_training_timesteps:\n","\n","    state = env.reset()\n","    current_ep_reward = 0\n","\n","    for t in range(1, max_ep_len+1):\n","\n","        # select action with policy\n","        action = ppo_agent.select_action(state)\n","        state, reward, done, _ = env.step(action)\n","\n","        # saving reward and is_terminals\n","        ppo_agent.buffer.rewards.append(reward)\n","        ppo_agent.buffer.is_terminals.append(done)\n","\n","        time_step +=1\n","        current_ep_reward += reward\n","\n","        # update PPO agent\n","        if time_step % update_timestep == 0:\n","            ppo_agent.update()\n","\n","        # if continuous action space; then decay action std of ouput action distribution\n","        if has_continuous_action_space and time_step % action_std_decay_freq == 0:\n","            ppo_agent.decay_action_std(action_std_decay_rate, min_action_std)\n","\n","        # log in logging file\n","        if time_step % log_freq == 0:\n","\n","            # log average reward till last episode\n","            log_avg_reward = log_running_reward / log_running_episodes\n","            log_avg_reward = round(log_avg_reward, 4)\n","\n","            log_f.write('{},{},{}\\n'.format(i_episode, time_step, log_avg_reward))\n","            log_f.flush()\n","\n","            log_running_reward = 0\n","            log_running_episodes = 0\n","\n","        # printing average reward\n","        if time_step % print_freq == 0:\n","\n","            # print average reward till last episode\n","            print_avg_reward = print_running_reward / print_running_episodes\n","            print_avg_reward = round(print_avg_reward, 2)\n","\n","            print(\"Episode : {} \\t\\t Timestep : {} \\t\\t Average Reward : {}\".format(i_episode, time_step, print_avg_reward))\n","\n","            print_running_reward = 0\n","            print_running_episodes = 0\n","\n","        # save model weights\n","        if time_step % save_model_freq == 0:\n","            print(\"--------------------------------------------------------------------------------------------\")\n","            print(\"saving model at : \" + checkpoint_path)\n","            ppo_agent.save(checkpoint_path)\n","            print(\"model saved\")\n","            print(\"Elapsed Time  : \", datetime.now().replace(microsecond=0) - start_time)\n","            print(\"--------------------------------------------------------------------------------------------\")\n","\n","        # break; if the episode is over\n","        if done:\n","            break\n","\n","    print_running_reward += current_ep_reward\n","    print_running_episodes += 1\n","\n","    log_running_reward += current_ep_reward\n","    log_running_episodes += 1\n","\n","    i_episode += 1\n","\n","\n","log_f.close()\n","\n","\n","\n","\n","# print total training time\n","print(\"============================================================================================\")\n","end_time = datetime.now().replace(microsecond=0)\n","print(\"Started training at (GMT) : \", start_time)\n","print(\"Finished training at (GMT) : \", end_time)\n","print(\"Total training time  : \", end_time - start_time)\n","print(\"============================================================================================\")\n","\n","\n","\n","\n","\n"]},{"cell_type":"markdown","metadata":{"id":"DHhK13_1G6zX"},"source":["> # **Part - III**\n","\n","*   load and test preTrained networks on environments"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true},"id":"SZWyhkq9Gxm5","outputId":"17c2c4aa-c788-4bc6-bbf4-02f1ec9a8985"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["============================================================================================\n","loading network from : PPO_preTrained/HEV/PPO_HEV_0_0.pth\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-16-b5c3479687dc>\", line 76, in <cell line: 76>\n","    ppo_agent.load(checkpoint_path)\n","  File \"<ipython-input-15-0ff9c0d4224d>\", line 303, in load\n","    self.policy_old.load_state_dict(torch.load(checkpoint_path, map_location=lambda storage, loc: storage))\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/serialization.py\", line 791, in load\n","    with _open_file_like(f, 'rb') as opened_file:\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/serialization.py\", line 271, in _open_file_like\n","    return _open_file(name_or_buffer, mode)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/serialization.py\", line 252, in __init__\n","    super().__init__(open(name, mode))\n","OSError: [Errno 107] Transport endpoint is not connected: 'PPO_preTrained/HEV/PPO_HEV_0_0.pth'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-16-b5c3479687dc>\", line 76, in <cell line: 76>\n","    ppo_agent.load(checkpoint_path)\n","  File \"<ipython-input-15-0ff9c0d4224d>\", line 303, in load\n","    self.policy_old.load_state_dict(torch.load(checkpoint_path, map_location=lambda storage, loc: storage))\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/serialization.py\", line 791, in load\n","    with _open_file_like(f, 'rb') as opened_file:\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/serialization.py\", line 271, in _open_file_like\n","    return _open_file(name_or_buffer, mode)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/serialization.py\", line 252, in __init__\n","    super().__init__(open(name, mode))\n","OSError: [Errno 107] Transport endpoint is not connected: 'PPO_preTrained/HEV/PPO_HEV_0_0.pth'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-16-b5c3479687dc>\", line 76, in <cell line: 76>\n","    ppo_agent.load(checkpoint_path)\n","  File \"<ipython-input-15-0ff9c0d4224d>\", line 303, in load\n","    self.policy_old.load_state_dict(torch.load(checkpoint_path, map_location=lambda storage, loc: storage))\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/serialization.py\", line 791, in load\n","    with _open_file_like(f, 'rb') as opened_file:\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/serialization.py\", line 271, in _open_file_like\n","    return _open_file(name_or_buffer, mode)\n","  File \"/usr/local/lib/python3.10/dist-packages/torch/serialization.py\", line 252, in __init__\n","    super().__init__(open(name, mode))\n","OSError: [Errno 107] Transport endpoint is not connected: 'PPO_preTrained/HEV/PPO_HEV_0_0.pth'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["\n","\n","print(\"============================================================================================\")\n","\n","\n","#################################### Testing ###################################\n","\n","\n","################## hyperparameters ##################\n","\n","env_name = \"HEV\"\n","has_continuous_action_space = True\n","max_ep_len = 180001\n","action_std = 0.6\n","\n","# env_name = \"CartPole-v1\"\n","# has_continuous_action_space = False\n","# max_ep_len = 400\n","# action_std = None\n","\n","\n","# env_name = \"LunarLander-v2\"\n","# has_continuous_action_space = False\n","# max_ep_len = 300\n","# action_std = None\n","\n","\n","# env_name = \"BipedalWalker-v2\"\n","# has_continuous_action_space = True\n","# max_ep_len = 1500           # max timesteps in one episode\n","# action_std = 0.1            # set same std for action distribution which was used while saving\n","\n","\n","# env_name = \"RoboschoolWalker2d-v1\"\n","# has_continuous_action_space = True\n","# max_ep_len = 1000           # max timesteps in one episode\n","# action_std = 0.1            # set same std for action distribution which was used while saving\n","\n","\n","total_test_episodes = 10    # total num of testing episodes\n","\n","K_epochs = 40               # update policy for K epochs\n","eps_clip = 0.2              # clip parameter for PPO\n","gamma = 0.99                # discount factor\n","\n","lr_actor = 0.0003           # learning rate for actor\n","lr_critic = 0.001           # learning rate for critic\n","\n","#####################################################\n","\n","\n","env = HEV(fmu_filename, start_time, stop_time, step_size, soc_init, vehicle_speed_profile)\n","\n","# state space dimension\n","state_dim = env.obssize\n","\n","# action space dimension\n","if has_continuous_action_space:\n","    action_dim = env.actsize\n","else:\n","    action_dim = env.action_space.n\n","\n","\n","# initialize a PPO agent\n","ppo_agent = PPO(state_dim, action_dim, lr_actor, lr_critic, gamma, K_epochs, eps_clip, has_continuous_action_space, action_std)\n","\n","\n","# preTrained weights directory\n","\n","random_seed = 0             #### set this to load a particular checkpoint trained on random seed\n","run_num_pretrained = 0      #### set this to load a particular checkpoint num\n","\n","\n","directory = \"PPO_preTrained\" + '/' + env_name + '/'\n","checkpoint_path = directory + \"PPO_{}_{}_{}.pth\".format(env_name, random_seed, run_num_pretrained)\n","print(\"loading network from : \" + checkpoint_path)\n","\n","ppo_agent.load(checkpoint_path)\n","\n","print(\"--------------------------------------------------------------------------------------------\")\n","\n","\n","\n","test_running_reward = 0\n","\n","for ep in range(1, total_test_episodes+1):\n","    ep_reward = 0\n","    state = env.reset()\n","\n","    for t in range(1, max_ep_len+1):\n","        action = ppo_agent.select_action(state)\n","        state, reward, done, _ = env.step(action)\n","        ep_reward += reward\n","\n","        if done:\n","            break\n","\n","    # clear buffer\n","    ppo_agent.buffer.clear()\n","\n","    test_running_reward +=  ep_reward\n","    print('Episode: {} \\t\\t Reward: {}'.format(ep, round(ep_reward, 2)))\n","    ep_reward = 0\n","\n","env.reset()\n","\n","\n","print(\"============================================================================================\")\n","\n","avg_test_reward = test_running_reward / total_test_episodes\n","avg_test_reward = round(avg_test_reward, 2)\n","print(\"average test reward : \" + str(avg_test_reward))\n","\n","print(\"============================================================================================\")\n","\n","\n","\n","\n","\n"]},{"cell_type":"markdown","metadata":{"id":"ZewQELovHFt4"},"source":["> # **Part - IV**\n","\n","*   load log files using pandas\n","*   plot graph using matplotlib"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true},"id":"bY-E5HGcGxiu","outputId":"5ca1d463-9610-4fc1-89a5-45de1d9b42b6"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["============================================================================================\n"]},{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-16-a09ea58be576>\", line 40, in <cell line: 39>\n","    os.makedirs(figures_dir)\n","  File \"/usr/lib/python3.10/os.py\", line 225, in makedirs\n","    mkdir(name, mode)\n","OSError: [Errno 107] Transport endpoint is not connected: 'PPO_figs'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-16-a09ea58be576>\", line 40, in <cell line: 39>\n","    os.makedirs(figures_dir)\n","  File \"/usr/lib/python3.10/os.py\", line 225, in makedirs\n","    mkdir(name, mode)\n","OSError: [Errno 107] Transport endpoint is not connected: 'PPO_figs'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]},{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-16-a09ea58be576>\", line 40, in <cell line: 39>\n","    os.makedirs(figures_dir)\n","  File \"/usr/lib/python3.10/os.py\", line 225, in makedirs\n","    mkdir(name, mode)\n","OSError: [Errno 107] Transport endpoint is not connected: 'PPO_figs'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["\n","import os\n","import pandas as pd\n","import matplotlib.pyplot as plt\n","\n","\n","print(\"============================================================================================\")\n","\n","env_name = 'HEV'\n","# env_name = 'LunarLander-v2'\n","# env_name = 'BipedalWalker-v2'\n","# env_name = 'RoboschoolWalker2d-v1'\n","\n","\n","fig_num = 0     #### change this to prevent overwriting figures in same env_name folder\n","\n","plot_avg = True    # plot average of all runs; else plot all runs separately\n","\n","fig_width = 10\n","fig_height = 6\n","\n","\n","# smooth out rewards to get a smooth and a less smooth (var) plot lines\n","window_len_smooth = 50\n","min_window_len_smooth = 1\n","linewidth_smooth = 1.5\n","alpha_smooth = 1\n","\n","window_len_var = 5\n","min_window_len_var = 1\n","linewidth_var = 2\n","alpha_var = 0.1\n","\n","\n","colors = ['red', 'blue', 'green', 'orange', 'purple', 'olive', 'brown', 'magenta', 'cyan', 'crimson','gray', 'black']\n","\n","\n","# make directory for saving figures\n","figures_dir = \"PPO_figs\"\n","if not os.path.exists(figures_dir):\n","    os.makedirs(figures_dir)\n","\n","# make environment directory for saving figures\n","figures_dir = figures_dir + '/' + env_name + '/'\n","if not os.path.exists(figures_dir):\n","    os.makedirs(figures_dir)\n","\n","\n","fig_save_path = figures_dir + '/PPO_' + env_name + '_fig_' + str(fig_num) + '.png'\n","\n","\n","# get number of log files in directory\n","log_dir = \"PPO_logs\" + '/' + env_name + '/'\n","\n","current_num_files = next(os.walk(log_dir))[2]\n","num_runs = len(current_num_files)\n","\n","\n","all_runs = []\n","\n","for run_num in range(num_runs):\n","\n","    log_f_name = log_dir + '/PPO_' + env_name + \"_log_\" + str(run_num) + \".csv\"\n","    print(\"loading data from : \" + log_f_name)\n","    data = pd.read_csv(log_f_name)\n","    data = pd.DataFrame(data)\n","\n","    print(\"data shape : \", data.shape)\n","\n","    all_runs.append(data)\n","    print(\"--------------------------------------------------------------------------------------------\")\n","\n","\n","ax = plt.gca()\n","\n","if plot_avg:\n","    # average all runs\n","    df_concat = pd.concat(all_runs)\n","    df_concat_groupby = df_concat.groupby(df_concat.index)\n","    data_avg = df_concat_groupby.mean()\n","\n","    # smooth out rewards to get a smooth and a less smooth (var) plot lines\n","    data_avg['reward_smooth'] = data_avg['reward'].rolling(window=window_len_smooth, win_type='triang', min_periods=min_window_len_smooth).mean()\n","    data_avg['reward_var'] = data_avg['reward'].rolling(window=window_len_var, win_type='triang', min_periods=min_window_len_var).mean()\n","\n","    data_avg.plot(kind='line', x='timestep' , y='reward_smooth',ax=ax,color=colors[0],  linewidth=linewidth_smooth, alpha=alpha_smooth)\n","    data_avg.plot(kind='line', x='timestep' , y='reward_var',ax=ax,color=colors[0],  linewidth=linewidth_var, alpha=alpha_var)\n","\n","    # keep only reward_smooth in the legend and rename it\n","    handles, labels = ax.get_legend_handles_labels()\n","    ax.legend([handles[0]], [\"reward_avg_\" + str(len(all_runs)) + \"_runs\"], loc=2)\n","\n","\n","else:\n","    for i, run in enumerate(all_runs):\n","        # smooth out rewards to get a smooth and a less smooth (var) plot lines\n","        run['reward_smooth_' + str(i)] = run['reward'].rolling(window=window_len_smooth, win_type='triang', min_periods=min_window_len_smooth).mean()\n","        run['reward_var_' + str(i)] = run['reward'].rolling(window=window_len_var, win_type='triang', min_periods=min_window_len_var).mean()\n","\n","        # plot the lines\n","        run.plot(kind='line', x='timestep' , y='reward_smooth_' + str(i),ax=ax,color=colors[i % len(colors)],  linewidth=linewidth_smooth, alpha=alpha_smooth)\n","        run.plot(kind='line', x='timestep' , y='reward_var_' + str(i),ax=ax,color=colors[i % len(colors)],  linewidth=linewidth_var, alpha=alpha_var)\n","\n","    # keep alternate elements (reward_smooth_i) in the legend\n","    handles, labels = ax.get_legend_handles_labels()\n","    new_handles = []\n","    new_labels = []\n","    for i in range(len(handles)):\n","        if(i%2 == 0):\n","            new_handles.append(handles[i])\n","            new_labels.append(labels[i])\n","    ax.legend(new_handles, new_labels, loc=2)\n","\n","\n","\n","# ax.set_yticks(np.arange(0, 1800, 200))\n","# ax.set_xticks(np.arange(0, int(4e6), int(5e5)))\n","\n","\n","ax.grid(color='gray', linestyle='-', linewidth=1, alpha=0.2)\n","\n","ax.set_xlabel(\"Timesteps\", fontsize=12)\n","ax.set_ylabel(\"Rewards\", fontsize=12)\n","\n","plt.title(env_name, fontsize=14)\n","\n","\n","fig = plt.gcf()\n","fig.set_size_inches(fig_width, fig_height)\n","\n","print(\"============================================================================================\")\n","\n","plt.savefig(fig_save_path)\n","print(\"figure saved at : \", fig_save_path)\n","\n","print(\"============================================================================================\")\n","\n","\n","plt.show()\n","\n","\n"]}],"metadata":{"accelerator":"GPU","colab":{"collapsed_sections":["e7JowRQEGGKQ","Z4VJcUT2GlJz"],"provenance":[{"file_id":"https://github.com/nikhilbarhate99/PPO-PyTorch/blob/master/PPO_colab.ipynb","timestamp":1687399399482}]},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}